name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - 3.12.7

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version}}
    
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Add Poetry to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry install
      working-directory: projects/task_1_remote_sensing_data

    - name: Run tests
      run: |
        poetry run python -m unittest discover tests
      working-directory: projects/task_1_remote_sensing_data
